import os
from dotenv import load_dotenv

load_dotenv()

POSTGRESQL_DRIVER_NAME = "postgresql"

POSTGRESQL_USER_NAME = "postgres"
POSTGRESQL_PASSWORD = "123456789"
POSTGRESQL_DB_NAME = "borderless"
POSTGRESQL_PORT_NO = 5432
POSTGRESQL_HOST = "192.168.12.98"

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_API_VERSION=os.getenv("AZURE_OPENAI_API_VERSION")

