POSTGRESQL_DRIVER_NAME = "postgresql"

# POSTGRESQL_USER_NAME = "postgres"
# POSTGRESQL_PASSWORD = "123456789"
# POSTGRESQL_DB_NAME = "borderless"
# POSTGRESQL_PORT_NO = 5432
# POSTGRESQL_HOST = "192.168.12.98"

SCHEMA_NAMES = ["EmailChunks"]

POSTGRESQL_USER_NAME = "postgres"
POSTGRESQL_PASSWORD = "12345"
POSTGRESQL_DB_NAME = "bla_ai"
POSTGRESQL_PORT_NO = 5432
POSTGRESQL_HOST = "localhost"