import os
from dotenv import load_dotenv

load_dotenv()

IMAGE_FORMATE = "jpeg"
IMAGE_RESOLUTION = 500
MAX_INPUT_TOKEN = 1000
TEMPERATURE = 0.0
AZURE_API_TYPE = "azure"
EMAIL_CLASSIFIER_AGENT_NAME="EmailClassifierAgent"
VALIDATOR_AGENT_NAME = "ValidatorAgent"
CONFIDENCE_AGENT_NAME ="ConfidenceAgent"
TIGGER_REASON_AGENT_NAME ="TriggerReasonAgent"
SUMMARIZATION_AGENT_NAME="SummarizationAgent"
AZURE_OPENAI_API_KEY=os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT= os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_VERSION=os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")
DEFAULT_IMAGE_FORMAT = ".jpg"
EMAIL_TO_PDF_PATH = "/data"
