trigger: none  # No auto-trigger (since no GitHub webhooks)

pool:
  name: Default
  demands:
    - agent.name -equals bap-agent

variables:
- group: GitHubAccess  # This links your GITHUB_USERNAME and GITHUB_TOKEN
- name: GITHUB_REPO
  value: 'zucisystems-dev/Borderless-workshop-cookbook-and-pilot'
- name: BRANCH
  value: 'master'

steps:
- script: |
    echo "Cloning repository..."
    git clone https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO).git --branch $(BRANCH)
    cd Borderless-workshop-cookbook-and-pilot/backend

    echo "Setting up virtual environment..."
    python3 -m venv venv
    source venv/bin/activate

    echo "Installing dependencies..."
    pip install --upgrade pip
    pip install -r requirements.txt

    echo "Running main.py"
    python main.py
  displayName: 'Clone and Run Python App'
